### ISSUE TITLE
media should go into its own folder

### ISSUE THREAD

**Issue by equilet** [adrianfreed/rdot#2]
examples:
- Cbass.res.sdif
- crotale-c5.res.sdif
- rPianoA-1.res.sdif
- rPianoA0.res.sdif
- rPianoA1.res.sdif
- rPianoA2.res.sdif
- rPianoA3.res.sdif
- rPianoA4.res.sdif
- rPianoA5.res.sdif
- rPianoA6.res.sdif

...these were in the `/help` folder, which is specifically for `.maxhelp`

**Comment by adrianfreed** [comment]
I couldn't make that work.
Bug in sdif loading code?

**Comment by equilet** [comment]
Let me check into it...

**Comment by adrianfreed** [comment]
I have max 7 configured wrong probably.
It seems to work in media with max 6

**Comment by equilet** [comment]
The files are located in `/help` currently.  Is that where you want them?

**Comment by adrianfreed** [comment]
I moved them into media.
Seems to work.
Can't test with Max 7

**Comment by equilet** [comment]
What loads them?  I can test...

I also moved them into `/media`.
AFAICT, they are in use by every one of the examples, so because I am hearing sound in r.rbfi for example, this can be marked as resolved?
Seems that they load fine in both `/help` and `/media`.

**Comment by adrianfreed** [comment]
sdif buffer

**Comment by equilet** [comment]
OK - looking good here.  I'm closing this out.
